### ISSUE TITLE
I have a question about the code

### ISSUE THREAD

**Issue by Sacare** [ChandlerBang/SimP-GCN#1]
About ‘Adaptive Integration’，in which file in the code is this function implemented，‘model’ or ‘layer’？ 
And in which methods is it implemented？Please tell me ，and thank you for your answer.

**Comment by ChandlerBang** [comment]
Hi,
Please see [`models_simp.py`](https://github.com/ChandlerBang/SimP-GCN/blob/main/src/models_simp.py). The function is implemented in `myforward()` of the class `GCNModel`.

**Comment by ChandlerBang** [comment]
A small update: to avoid confusion, I have changed the name of `GCNModel` to `SimPGCN`.
