### ISSUE TITLE
About pubmed dataset result

### ISSUE THREAD

**Issue by xh3204** [ChandlerBang/SimP-GCN#3]
I want to reproduce the result on the PubMed dataset with a 0.00 perturbation rate. However, I can't get the same results recorded in your paper while I just modify the ptb_rate to 0 in the .sh file. Does there need another hyperparameters setting since the providing .sh file corresponds to ptb_rate = 0.15?

**Comment by ChandlerBang** [comment]
Hi,

If you set `ptb_rate` to 0, the loaded datasets will be using the default splits in Table 1 (20 nodes per class for training).

As shown in [sample.py](https://github.com/ChandlerBang/SimP-GCN/blob/main/src/sample.py#L26-L37), you can set `ptb_rate` to 10 to get the result on clean dataset with 10%/10%/80% for traininig/validation/test.

Thanks.
