### ISSUE TITLE
How to use my own dataset.

### ISSUE THREAD

**Issue by sawyerfeng** [ChandlerBang/SimP-GCN#4]
I tried to use my own data but don't know the way.

**Comment by ChandlerBang** [comment]
You can follow the way we load perturbed dataset: 
https://github.com/ChandlerBang/SimP-GCN/blob/0aa4b8950db0d6a385e5b716164b545fa931800a/src/sample.py#L26-L31

Basically, you need to have `self.adj, self.features, self.labels` and ` self.idx_train, self.idx_val, self.idx_test`.

**Comment by sawyerfeng** [comment]
Thanks a lot.
