### ISSUE TITLE
codes for Table 1

### ISSUE THREAD

**Issue by liaoJing56** [ChandlerBang/SimP-GCN#5]
Hello, I would like to ask about the reproduce of Table 1. How do I reproduce the results? Generate the adjacency matrix and calculate the percentage by myself or am I missing something?

**Comment by liaoJing56** [comment]
In addition, taking the cora data set as an example, the number of edges in the KNN graph is the number of nodes multiplied by k. If k is 20, the number of edges is 2708*20=54160, and the edges of cora's original adjacency matrix are 10556.
The number of these two edges is too far apart and may not be suitable for calculating the percentage together. Is my k value wrong or why?
Looking forward to your answer.

**Comment by ChandlerBang** [comment]
Hi, sorry for the late reply. 

To calculate the OL metric, you can refer to Eq. (7) and more details are given in Section 3.2. For example, k is set to 3 and the denominator is either A_f or A_h which have the same number of edges.

**Comment by liaoJing56** [comment]
Thank you very much for your reply and wish you all the best.
