### ISSUE TITLE
reproduce problem

### ISSUE THREAD

**Issue by yaominghong** [ChandlerBang/SimP-GCN#6]
Hello,I try to reproduce the result.Other datesets are ok,but there are two problems in reproducing Cora.
![problem](https://user-images.githubusercontent.com/18033055/143477462-420ead06-6984-4981-88db-fcc6188f0d6b.png)
I searched some solutions about relative problems,but can't fix it.
So I ask for your help.Thank you.

**Comment by ChandlerBang** [comment]
Hi, can you tell me about the command you used? Seems you are loading the largest connected component (with 2485 nodes) instead of the full graph (2708 nodes).

**Comment by yaominghong** [comment]
I used **python run.py** command.

**Comment by ChandlerBang** [comment]
Did this bug happen at the adversarial robustness experiments? 

Did you remove the files in `saved/`? In adversarial robustness experiments, we only use the largest component of the graphs. This is different from the normal setting; so the saved KNN graph cannot be reused.

https://github.com/ChandlerBang/SimP-GCN/blob/3022380aa77f5750ede16a35edf53152a4891334/run.py#L81-L85

**Comment by yaominghong** [comment]
I successfully run it.Thank you so much.I've learned a lot from your work.

**Comment by ChandlerBang** [comment]
Great! Glad it helped.

**Comment by LuYuanGao1017** [comment]
> I successfully run it.Thank you so much.I've learned a lot from your work.
Hello, I also have your two questions. Can you tell me how to solve it? I don't know where to delete saved/
