### ISSUE TITLE
some function is not defined

### ISSUE THREAD

**Issue by LuYuanGao1017** [ChandlerBang/SimP-GCN#7]
Hello I am a beginner. See the code address from your paper. There are some problems here：
In models_simp.py there GraphConvolution and GCFlatResBlock not defined
And in normalization.py  
![image](https://user-images.githubusercontent.com/91652776/144700203-a1b2ec90-b6dc-45d9-8370-1a85fd2396b6.png)
Can these problems be solved if I download deeprobust？

**Comment by ChandlerBang** [comment]
Hi, some of the code is adopted from [DropEdge](https://github.com/DropEdge/DropEdge) and is not really used in this project. Thus, you may just ignore the ` GCNFlatRes` class.

**Comment by LuYuanGao1017** [comment]
Very happy to see your reply early in the morning. If possible, can I add your WeChat for some academic discussions?I am a fresh graduate student, my research direction is complex network node classification。

**Comment by ChandlerBang** [comment]
sure. you can contact me on joe.weijin@gmail.com for more information

**Comment by LuYuanGao1017** [comment]
Hello, I have some questions in the follow-up, can I communicate with you in Chinese? I feel that expressing in Chinese may convey my thoughts more accurately. Your paper is the most fluent one I have read. The logical structure is very clear. According to my current knowledge reserve, the question I asked may be a little silly for you. I hope to be able to communicate with you in your free time, and if possible, I would like to hear about your learning experience. Regarding your paper, I think it might be easier for people to understand if there is a structure diagram like LeNet-5.Finally, thank you again for replying to me.😄

**Comment by ChandlerBang** [comment]
Sure.
